server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deepfake?severTimezone=GMT%2b8
    username: root //改为自己的数据库用户名
    password: root root  //数据库密码

mybatis:
  mapper-locations: D:\开发工作\deepfakes\springboot\src\main\java\com\example\springboot\gen\mapper\xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
